### PR TITLE
[GAP_pkg_juliainterface] Rebuild with GAP 4.15.0

### PR DESCRIPTION
**Pull request by lgoettgens**
Companion to https://github.com/JuliaPackaging/Yggdrasil/pull/11987.

I am getting the following build failure locally:
```julia
[16:32:07]  ---> cd GAP.jl/pkg/JuliaInterface
[16:32:07]  ---> ./configure --with-gaproot=${prefix}/lib/gap
[16:32:07]  ---> make CFLAGS="-I${includedir} -I${includedir}/julia" LDFLAGS="-ljulia -lgap" V=1
[16:32:07] src/JuliaInterface.c:19:10: fatal error: julia_gc.h: No such file or directory
[16:32:07]  #include <julia_gc.h>    // GAP header
[16:32:07]           ^~~~~~~~~~~~
[16:32:07] compilation terminated.
[16:32:07] make: *** [Makefile.gappkg:119: gen/src/JuliaInterface.o] Error 1
[16:32:07]  ---> make CFLAGS="-I${includedir} -I${includedir}/julia" LDFLAGS="-ljulia -lgap" V=1
[16:32:07]  ---> make CFLAGS="-I${includedir} -I${includedir}/julia" LDFLAGS="-ljulia -lgap" V=1
[16:32:07] Previous command exited with 2
[16:32:07] Child Process exited, exit code 2
```

I remebember seeing discussions about gap headers somewhere, but I don't find it anymore nor is there something in the release notes. This could also be related to https://github.com/JuliaPackaging/Yggdrasil/pull/11987#discussion_r2313918603. @fingolfin do you have an idea what's going on here?

### CODE REVIEW

**Comment by fingolfin** [comment]
Uhh, I think that's a fallout of recent changes meant to help improve compatibility with Mingw / Windows.

Anyway, as a quick workaround, we could apply a patch here to change `#include <julia_gc.h>` to `#include <gap/julia_gc.h>`

**Comment by giordano** [comment]
> Uhh, I think that's a fallout of recent changes meant to help improve compatibility with Mingw / Windows.

You mean in Gap or BinaryBuilder? Today I did run into an issue caused by us fixing the MinGW header files (we had been incorrectly loading the v7 ones for ages, when we had the v11 available: https://github.com/JuliaPackaging/Yggdrasil/pull/11878#issuecomment-3200452721), but at a quick glance the error above feels completely different.

**Comment by lgoettgens** [comment]
> > Uhh, I think that's a fallout of recent changes meant to help improve compatibility with Mingw / Windows.
> 
> You mean in Gap or BinaryBuilder? Today I did run into an issue caused by us fixing the MinGW header files (we had been incorrectly loading the v7 ones for ages, when we had the v11 available: [#11878 (comment)](https://github.com/JuliaPackaging/Yggdrasil/pull/11878#issuecomment-3200452721)), but at a quick glance the error above feels completely different.

In gap.



> Anyway, as a quick workaround, we could apply a patch here to change `#include <julia_gc.h>` to `#include <gap/julia_gc.h>`

The main thing I was confused about is that this is somehow just needed here in yggy, but not in the gap downstream tests (e.g. https://github.com/gap-system/gap/actions/runs/17328521155/job/49198671037#step:8:346). But due to this fact, my other question if this should be an yggy patch or a change to the juliainterface code is resolved (to the former option).

I was also thinking that similar issues could happen for other gap packages with kernel extensions (at least in yggy; and patching all includes in all of them doesn't seem to be a great solution to me)

**Comment by lgoettgens** [comment]
> > Anyway, as a quick workaround, we could apply a patch here to change `#include <julia_gc.h>` to `#include <gap/julia_gc.h>`
> 
> The main thing I was confused about is that this is somehow just needed here in yggy, but not in the gap downstream tests (e.g. [gap-system/gap/actions/runs/17328521155/job/49198671037#step:8:346](https://github.com/gap-system/gap/actions/runs/17328521155/job/49198671037#step:8:346)). But due to this fact, my other question if this should be an yggy patch or a change to the juliainterface code is resolved (to the former option).
> 
> I was also thinking that similar issues could happen for other gap packages with kernel extensions (at least in yggy; and patching all includes in all of them doesn't seem to be a great solution to me)

I just read through https://github.com/gap-system/gap/pull/6007 and iiuc this should only affect gap kernel extensions that include specific headers (and not `gap_all.h`), so the breakage should be minimal. I have a small patch for juliainterface and GAP.jl that I'll try to get into this build here.

**Comment by lgoettgens** [comment]
Closing as this has conflicts with the versioning scheme in https://github.com/JuliaPackaging/Yggdrasil/pull/12032. I instead incorporated the commits there.
