### PR TITLE
[PETSc] Upgrades petsc to 3.15.2 and enables multiple precision, scalar, and int types

### PR DESCRIPTION
**Pull request by jkozdon**
- Upgrades PETSc to 3.15.2
- Allows for 8 different build options:
  - Scalar Types: `complex` and `real`
  - Real Types: `Float64` and `Float32`
  - Int Types: `Int32` and `Int64`

The libraries named:
- `libpetsc_Float64_Real_Int64`
- `libpetsc_Float32_Real_Int64`
- `libpetsc_Float64_Complex_Int64`
- `libpetsc_Float32_Complex_Int64`
- `libpetsc_Float64_Real_Int32`
- `libpetsc_Float32_Real_Int32`
- `libpetsc_Float64_Complex_Int32`
- `libpetsc_Float32_Complex_Int32`

Additionally, there is a library `libpetsc` which is the same as `libpetsc_double_real_Int32` (the current default version of `PETSc_jll`).

### CODE REVIEW

**Comment by giordano** [comment]
`i686-linux-*` and `x86_64-linux-*` is an incredibly bizarre set of platforms that would fail, since these are the only platforms for which we can actually do native compilation (`i686-linux-musl` is actually broken for C++ and Fortran, but can run pure C applications)

**Comment by jkozdon** [comment]
> `i686-linux-*` and `x86_64-linux-*` is an incredibly bizarre set of platforms that would fail, since these are the only platforms for which we can actually do native compilation (`i686-linux-musl` is actually broken for C++ and Fortran, but can run pure C applications)

Any tips for working around this?

**Comment by giordano** [comment]
If you haven't done that yet, I'd suggest to locally enter the build environment and read the log files, to understand what's going on:
```
julia build_tarballs.jl --debug --verbose x86_64-linux-gnu-libgfortran5
```
PETSc has a super custom build system, so I can't easily try and guess something.  But the fact that only these platforms fail is very remarkable, it's the exact opposite of what I'd expect in general: platforms that can do native compilation should be easier to deal with in our cross-compilation framework.

**Comment by jkozdon** [comment]
> If you haven't done that yet, I'd suggest to locally enter the build environment and read the log files

Will do. I misread you previous message, and thought that you were suggesting that failure was likely.

**Comment by jkozdon** [comment]
Hmm... doesn't even work without my changes so the problem is some change outside of PETSc. Going to try to enlist someone who is better at build systems than me.

In case anyone is interested here is what I am doing to just try `i686-linux-gnu-libgfortran3`

- [build command](https://gist.github.com/jkozdon/c161fb15f2df23c3fbc0a5a095887ef8#file-build_command-sh)
- [`build_tarballs.jl`](https://gist.github.com/jkozdon/c161fb15f2df23c3fbc0a5a095887ef8#file-build_tarballs-jl)
- [`configure.log`](https://gist.github.com/jkozdon/c161fb15f2df23c3fbc0a5a095887ef8#file-configure-log)
- [`output.log`](https://gist.github.com/jkozdon/c161fb15f2df23c3fbc0a5a095887ef8#file-output-log)
- [`bundled/patches/petsc_name_mangle.patch`](https://gist.github.com/jkozdon/c161fb15f2df23c3fbc0a5a095887ef8#file-petsc_name_mangle-patch)

One of the weird things to me is that there are errors like
[`/workspace/destdir/lib/libstdc++.so: undefined reference to `__divmoddi4@GCC_7.0.0'`](https://gist.github.com/jkozdon/c161fb15f2df23c3fbc0a5a095887ef8#file-configure-log-L7795)

**Comment by jkozdon** [comment]
Folks on the [petsc mailing list](https://lists.mcs.anl.gov/pipermail/petsc-users/2021-July/044028.html) think that there is a problem with the compiler install given the reference to `__divmoddi4@GCC_7.0.0'` in `libstdc++.so`.

Could there be some issue with `CompilerSupportLibraries_jll`? I did notice that it was updated with #3198 but MPICH hasn't been update yet. When I tried my own newly deployed version of MPICH this didn't help though, so I guess that's not an issue 🤷‍♂️ .

If I turn off the c++ interface with `--wtih-cxx=0` things seem to build fine, the downside of this is that future building with external packages might be hindered.

**Comment by jkozdon** [comment]
I have reverted all my commits and just rolled back the `CompilerSupportLibraries_jll` to right before #3198 which allows the current version of `PETSc_jll` to build. (Prior to this the build of `PETSc_jll` on `master` fails.)

- Rolled back `CompilerSupportLibraries_jll`: 21ca17b [build](https://github.com/JuliaPackaging/Yggdrasil/runs/2975500067)
- forced rebuild of master: fd31800 [build](https://github.com/JuliaPackaging/Yggdrasil/runs/2975533083)

So it seems that there is something that broken with the c++ libraries with #3198(?), though #3198 seems so minimal I have no idea what could be wrong.

Not sure how to proceed.... Thoughts?

**Comment by giordano** [comment]
Uhm, the fact that libstdc++ from GCC 11 may be relevant is interesting and concerning, since that's what will be used in Julia v1.7.  Rolling back `CompilerSupportLibraries_jll` isn't much useful, that's a set of libraries that are really important only at runtime, not much during the build (compilers shard already come with those libraries).  I need to investigate what's going on here, but it'll take a few days.

**Comment by jkozdon** [comment]
> I need to investigate what's going on here, but it'll take a few days.

Thanks.

**Comment by giordano** [comment]
For the record, I believe I tracked down the issue to the simple reproducer I reported in https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/163 and I already have a fix for that, but I need to write the tests and that may take a bit as it's surprisingly complicated to do in a nice way (by "nice" I mean in a way that doesn't force me to download the `CompilerSupportLibraries_jll` tarball every time).  I'm moderately confident that should fix also the issues we have here (at least the symptoms are the same) but I haven't tried to build PETSc with that.  Thanks for the patience!

**Comment by jkozdon** [comment]
@giordano Thanks for the update! No rush, I appreciate you taking a look.

**Comment by giordano** [comment]
Ok, it looks like https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/163 did solve the issues with `i686-linux-*-libgfortran3` :slightly_smiling_face:

**Comment by jkozdon** [comment]
Thanks!

**Comment by giordano** [comment]
`i686-linux-musl-libgfortran3` failed with
```
[00:17:55] i686-linux-musl_double_real_Int32/obj/sys/logging/plog.o: In function `PetscLogInitialize':
[00:17:55] plog.c:(.text+0xbe8): undefined reference to `__stack_chk_fail_local'
[00:17:55] i686-linux-musl_double_real_Int32/obj/sys/logging/plog.o: In function `PetscLogDump':
[00:17:55] plog.c:(.text+0x2683): undefined reference to `__stack_chk_fail_local'
[00:17:55] i686-linux-musl_double_real_Int32/obj/sys/logging/plog.o: In function `PetscLogView_Detailed':
[00:17:55] plog.c:(.text+0x35c0): undefined reference to `__stack_chk_fail_local'
[00:17:55] i686-linux-musl_double_real_Int32/obj/sys/logging/plog.o: In function `PetscLogView_CSV':
[00:17:55] plog.c:(.text+0x3e8d): undefined reference to `__stack_chk_fail_local'
[00:17:55] i686-linux-musl_double_real_Int32/obj/sys/logging/plog.o: In function `PetscLogView_Default':
[00:17:55] plog.c:(.text+0x7633): undefined reference to `__stack_chk_fail_local'
[00:17:55] i686-linux-musl_double_real_Int32/obj/sys/logging/plog.o:plog.c:(.text.unlikely+0x9a): more undefined references to `__stack_chk_fail_local' follow
[00:17:55] collect2: error: ld returned 1 exit status
[00:17:55] make[3]: *** [gmakefile:113: i686-linux-musl_double_real_Int32/lib/libpetsc.so.3.15.2] Error 1
[00:17:55] make[2]: *** [/workspace/srcdir/petsc-3.15.2/lib/petsc/conf/rules:50: libs] Error 2
```
The same error with undefined reference to `__stack_chk_fail_local` was reported in https://github.com/JuliaPackaging/Yggdrasil/pull/845#issuecomment-673116280.  The workaround there was removing superlu (not really a fix...).

**Comment by jkozdon** [comment]
> The same error with undefined reference to `__stack_chk_fail_local` was reported in [#845 (comment)](https://github.com/JuliaPackaging/Yggdrasil/pull/845#issuecomment-673116280). The workaround there was removing superlu (not really a fix...).

Unfortunately superlu is already turned off. Going to work on trying to debug locally.

**Comment by jkozdon** [comment]
Yup. That's what I was thinking. We're getting there!

Will do some more debugging later locally on the failing ones to see if I can figure anything out.

**Comment by jkozdon** [comment]
Updated local outputs: https://gist.github.com/jkozdon/c161fb15f2df23c3fbc0a5a095887ef8

**Comment by giordano** [comment]
So, I spent only 5 minutes trying to debug this, but this seems relevant:
```
===== Checking linker
Executing: cc -c -o /tmp/petsc-iw71nbk0/config.libraries/conftest.o -I/tmp/petsc-iw71nbk0/config.compilerFlags -I/tmp/petsc-iw71nbk0/config.setCompilers -I/tmp/petsc-iw71nbk0/config.compilers -I/tmp/petsc-iw71nbk0/config.utilities.closure -I/tmp/petsc-iw71nbk0/config.headers -I/tmp/petsc-iw71nbk0/config.utilities.cacheDetails -I/tmp/petsc-iw71nbk0/config.types -I/tmp/petsc-iw71nbk0/config.functions -I/tmp/petsc-iw71nbk0/config.utilities.featureTestMacros -I/tmp/petsc-iw71nbk0/config.utilities.missing -I/tmp/petsc-iw71nbk0/PETSc.options.sharedLibraries -I/tmp/petsc-iw71nbk0/config.libraries -I/tmp/petsc-iw71nbk0/PETSc.options.scalarTypes -fno-stack-protector -fPIC -O3   /tmp/petsc-iw71nbk0/config.libraries/conftest.c 
Successful compile:
Source:
#include "confdefs.h"
#include "conffix.h"
/* Override any gcc2 internal prototype to avoid an error. */
char MPI_Init();
static void _check_MPI_Init() { MPI_Init(); }
char MPI_Comm_create();
static void _check_MPI_Comm_create() { MPI_Comm_create(); }

int main() {
_check_MPI_Init();
_check_MPI_Comm_create();;
  return 0;
}
Executing: cc  -o /tmp/petsc-iw71nbk0/config.libraries/conftest   -fno-stack-protector -fPIC -O3 /tmp/petsc-iw71nbk0/config.libraries/conftest.o  -Wl,-rpath,/workspace/destdir/lib -L/workspace/destdir/lib -lmpifort -Wl,-rpath,/workspace/destdir/lib -L/workspace/destdir/lib -lmpi -lquadmath -lstdc++ -ldl 
Possible ERROR while running linker:
stderr:
/opt/i686-linux-musl/bin/../lib/gcc/i686-linux-musl/8.1.0/../../../../i686-linux-musl/bin/ld: warning: /workspace/destdir/lib/libgfortran.so.5: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/opt/i686-linux-musl/bin/../lib/gcc/i686-linux-musl/8.1.0/../../../../i686-linux-musl/bin/ld: warning: /workspace/destdir/lib/libgfortran.so.5: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/opt/i686-linux-musl/bin/../lib/gcc/i686-linux-musl/8.1.0/../../../../i686-linux-musl/bin/ld: warning: /opt/i686-linux-musl/bin/../i686-linux-musl/sys-root/usr/local/lib/libgfortran.so.5: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/opt/i686-linux-musl/bin/../lib/gcc/i686-linux-musl/8.1.0/../../../../i686-linux-musl/bin/ld: warning: /opt/i686-linux-musl/bin/../i686-linux-musl/sys-root/usr/local/lib/libgfortran.so.5: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
```
As far as I understand, the linker works fine but emits a warning printed to `stderr`, but in that case the configure scripts errors out even if there is nothing wrong: https://gitlab.com/petsc/petsc/-/blob/4204ec6bd09c0f6df882d207f007f8d92faa2086/config/BuildSystem/config/base.py#L607-L610 :shrug:

**Comment by giordano** [comment]
We bundle GCC and binutils together, you can see the mapping at https://github.com/JuliaPackaging/Yggdrasil/blob/c444199d51afa2effc5b3f4fa228cfc4bef74b07/0_RootFS/gcc_common.jl#L156-L166 So I thought that maybe the linker we bring together with GCC 8 wasn't nice enough and I tried GCC 9, but then configure fails because it tries to do this:
```
===== Checking linker
Executing: cc -c -o /tmp/petsc-nfxkbmoq/config.libraries/conftest.o -I/tmp/petsc-nfxkbmoq/config.compilerFlags -I/tmp/petsc-nfxkbmoq/config.setCompilers -I/tmp/petsc-nfxkbmoq/config.compilers -I/tmp/petsc-nfxkbmoq/config.utilities.closure -I/tmp/petsc-nfxkbmoq/config.headers -I/tmp/petsc-nfxkbmoq/config.utilities.cacheDetails -I/tmp/petsc-nfxkbmoq/config.types -I/tmp/petsc-nfxkbmoq/config.functions -I/tmp/petsc-nfxkbmoq/config.utilities.featureTestMacros -I/tmp/petsc-nfxkbmoq/config.utilities.missing -I/tmp/petsc-nfxkbmoq/PETSc.options.sharedLibraries -I/tmp/petsc-nfxkbmoq/config.libraries -I/tmp/petsc-nfxkbmoq/PETSc.options.scalarTypes -fno-stack-protector -fPIC -O3   /tmp/petsc-nfxkbmoq/config.libraries/conftest.c 
Successful compile:
Source:
#include "confdefs.h"
#include "conffix.h"
/* Override any gcc2 internal prototype to avoid an error. */
char MPI_Init();
static void _check_MPI_Init() { MPI_Init(); }
char MPI_Comm_create();
static void _check_MPI_Comm_create() { MPI_Comm_create(); }

int main() {
_check_MPI_Init();
_check_MPI_Comm_create();;
  return 0;
}
Executing: cc  -o /tmp/petsc-nfxkbmoq/config.libraries/conftest   -fno-stack-protector -fPIC -O3 /tmp/petsc-nfxkbmoq/config.libraries/conftest.o  -Wl,-rpath,/workspace/destdir/lib -L/workspace/destdir/lib -lmpifort -Wl,-rpath,/workspace/destdir/lib -L/workspace/destdir/lib -lmpi -lquadmath -lstdc++ -ldl 
Possible ERROR while running linker: exit code 1
stderr:
/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/10.2.0/../../../../x86_64-linux-musl/bin/ld: /usr/lib/csl-glibc-x86_64/libgfortran.so.5: undefined reference to `sinhq@QUADMATH_1.0'
/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/10.2.0/../../../../x86_64-linux-musl/bin/ld: /usr/lib/csl-glibc-x86_64/libgfortran.so.5: undefined reference to `erfcq@QUADMATH_1.0'
/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/10.2.0/../../../../x86_64-linux-musl/bin/ld: /usr/lib/csl-glibc-x86_64/libgfortran.so.5: undefined reference to `acosq@QUADMATH_1.0'
/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/10.2.0/../../../../x86_64-linux-musl/bin/ld: /usr/lib/csl-glibc-x86_64/libgfortran.so.5: undefined reference to `tanq@QUADMATH_1.0'
/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/10.2.0/../../../../x86_64-linux-musl/bin/ld: /usr/lib/csl-glibc-x86_64/libgfortran.so.5: undefined reference to `jnq@QUADMATH_1.0'
/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/10.2.0/../../../../x86_64-linux-musl/bin/ld: /usr/lib/csl-glibc-x86_64/libgfortran.so.5: undefined reference to `strtoflt128@QUADMATH_1.0'
[...]
```
It compiles the test C program with _both_ libraries, but one is for C the other is Fortran and it doesn't use `-lgfortran` for the Fortran library :confused:  I have no idea how this works at all in the other platforms :confused:

**Comment by jkozdon** [comment]
Thanks for your help @giordano.

**Comment by giordano** [comment]
If this is ready, you should mark it so :slightly_smiling_face:

However auditor reports a warning about the fact there are two files with the same path, module case: they generate two identical pkgconfig files with names `PETSc.pc` and `petsc.pc`: https://gitlab.com/petsc/petsc/-/blob/4204ec6bd09c0f6df882d207f007f8d92faa2086/config/PETSc/Configure.py#L981-L982.  This can be a problem on case-insensitive file-systems, especially since `Pkg` will check the git-tree-sha1 of the unpacked tarball, and this check may fail.

@jedbrown I see you [introduced the `petsc.pc` file](https://gitlab.com/petsc/petsc/-/commit/8244ab14c2e21e12ee103991a08e32bcb3146af5): do you think it's a good idea for us to remove the `PETSc.pc` file?

**Comment by jedbrown** [comment]
The PETSc installer writes `PETSc.pc` first and then `petsc.pc`, which should replace the first if the filesystem is case insensitive. This was intended for backward compatibility, which I don't think Julia cares about.

**Comment by giordano** [comment]
Yeah, the fact is that here we create the tarballs on a case-sensitive file-system but will install the tarballs on case-insensitive ones :slightly_smiling_face:  But yeah, should we have troubles with other packages not finding PETSc we can fix that

**Comment by jkozdon** [comment]
The whole point of the PR was to enable multiple scalar, real, and int type versions of PETSc.

I'm building these right now to make sure that they work fine before releasing the PR

**Comment by jedbrown** [comment]
Cool, @giordano If you think PETSc upstream should do something differently, let us know. I figure we can remove `PETSc.pc` at some point in the future, but it would be somewhat disruptive to existing users to do it now.

**Comment by jkozdon** [comment]
OK. I think that I am happy with this now.

- I've re-enabled the mult-lib build
- Fixed the PR description
- Cleaned up the commit history some

**Comment by jkozdon** [comment]
Would it be worth also adding debug versions of the library? That blows up the build even more though...

cc: @psanan, @boriskaus, @simonbyrne ?

**Comment by boriskaus** [comment]
As far as I am concerned I would be extremely happy to have builds with superlu_dist and mumps included; we use that as coarse grid solvers in basically everything we do.

Debug would be lower in this list.

On 14. Jul 2021, at 19:11, Jeremy E Kozdon ***@***.***> wrote:

﻿

Would it be worth also adding debug versions of the library? That blows up the build even more though...

cc: @psanan<https://github.com/psanan>, @boriskaus<https://github.com/boriskaus>, @simonbyrne<https://github.com/simonbyrne> ?

**Comment by jkozdon** [comment]
Let me see if I can enable these...

**Comment by jkozdon** [comment]
It's looking like mumps, superlu, and superlu_dist will take a bit of work to sort out.

I know that superlu didn't work before either in the original PETSc PR #845

**Comment by giordano** [comment]
The only thing I'd like to ask is to delete `${prefix}/lib/PETSc.pc` at the end of the build, to avoid problems on Windows and macOS, as discussed above.  After that, this would be good to go from me.

**Comment by jkozdon** [comment]
🎉  Thanks!

**Comment by psanan** [comment]
@jkozdon re whether debug builds should be included, this depends on whether users will need the extra checks that debug mode provides. In normal PETSc usage, this adds more checks that `Vec`s are the right size, pointers are non-`NULL`, etc.
