### PR TITLE
Add MMseqs2 build script

### PR DESCRIPTION
**Pull request by marcom**
This is a build script for mmseqs2, a many-to-many sequence searching tool for bioinformatics:

https://github.com/soedinglab/MMseqs2

Notes:

- not sure if the way i switched `CMAKE_TARGET_TOOLCHAIN` on macos and freebsd is the right way to do it
- I added the dependencies Zlib and Bzip2 by hand, so i don't have any uuids there. Is this a problem?
- ARM doesn't have vectorization acceleration due to the -march issues noted in the build script
- I chose g++-8, because g++-7 didn't compile on powerpc. A build with g++-11 resulted in binaries that didn't work on Ubuntu 20.04 due to newer GLIBCXX symbols used
- freebsd has a warning from the BinaryBuilder auditor: `Warning: Linked library libomp.so could not be resolved and could not be auto-mapped`. I don't have a freebsd system so i can't test if the built binary actually works there

### CODE REVIEW

File: M/MMseqs2/build_tarballs.jl [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+# Build failures
+# - windows:
+#   - cmake can't find openmp, this check can be avoided by passing -DREQUIRE_OPENMP=0 to cmake
+#   - compile error afterwards
+#     error: ‘posix_memalign’ was not declared in this scope
+#     (and more following errors)
+# - i686: compile error due to bitwidth issues, haven't investigated more
+# - aarch64-linux with cmake option -DHAVE_ARM8=1, had to deactivate
+#   - compile wants to set -march=armv8-a+simd, but BinaryBuild
+#     wrappers don't allow that
```
Comment (giordano) [inline M/MMseqs2/build_tarballs.jl:30]: I'm not really sure why they force `-march` that way, as far as I understand that's [pretty much equivalent](https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html) to just `-march=armv8-a` which is the base architecture anyways.  We could disable the check for `-march`, but I'd prefer simply patching the CMake file to remove the line https://github.com/soedinglab/MMseqs2/blob/efacc6904ce3654110d1878943e16ddd0e7b1280/CMakeLists.txt#L73, it's just useless

File: M/MMseqs2/build_tarballs.jl [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+mkdir build
+cd build
+cmake .. \
+    -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=RELEASE \
+    -DNATIVE_ARCH=0 ${ARCH_FLAGS}
+make -j${nproc}
+make install
+
+cd ..
+install_license LICENSE.md
```
Comment (giordano) [inline M/MMseqs2/build_tarballs.jl:73]:
```suggestion
install_license ../LICENSE.md
```

**Comment by marcom** [comment]
Many thanks for the review. I have made the changes, and ran the build for all platforms locally as well tested with `--deploy=local` for `x86_64-linux-gnu`. Not sure why the CI tests are failing.

File: M/MMseqs2/build_tarballs.jl [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+    -DNATIVE_ARCH=0 ${ARCH_FLAGS}
+make -j${nproc}
+make install
+
+install_license ../LICENSE.md
+"""
+
+# These are the platforms we will build for by default, unless further
+# platforms are passed in on the command line
+platforms = supported_platforms(exclude = p -> Sys.iswindows(p) || arch(p) == "i686")
```
Comment (giordano) [inline M/MMseqs2/build_tarballs.jl:77]: Let's try experimental platforms:
```suggestion
platforms = supported_platforms(; experimental=true, exclude = p -> Sys.iswindows(p) || arch(p) == "i686")
```

**Comment by giordano** [comment]
The build for `aarch64-apple-darwin` is trying to use SSE instructions, sigh.  I don't have the time to dig this out, up to you whether to try and solve the issue or just disable this platform.

**Comment by marcom** [comment]
I'll have a look, the build on powerpc failed in the same way with g++-7 but works with g++ >= 8, so maybe switching to a newer g++ will help. Should i in general try and build on experimental platforms as well when submitting other build scripts?

**Comment by giordano** [comment]
> so maybe switching to a newer g++ will help

I don't think so, for `aarch64-apple-darwin` we have only GCC 11 (the "preferred" GCC version is only a hint, the actual version used may be different, depending on some platform-dependent constraints).  My suspect is that something in the build system assumes that macOS is only x86-64.  Again, don't worry if you think this is too much work, we can simply disable this platform for the time being.

> Should i in general try and build on experimental platforms as well when submitting other build scripts?

If possible, yes, thanks :slightly_smiling_face:  In the future we'll likely make `experimental=true` by default.

**Comment by Crghilardi** [comment]
It looks like it's erroring out at the [ksw2 lib file](https://github.com/soedinglab/MMseqs2/blob/master/lib/ksw2/ksw2_extz2_sse.cpp#L35) which only shows a `x86` include In the [Azure pipeline](https://github.com/soedinglab/MMseqs2/blob/efacc6904ce3654110d1878943e16ddd0e7b1280/util/build_osx.sh#L59-L70). They show an `arm64` build but I can't tell how those flags are different than what is already being used.

**Comment by marcom** [comment]
I got `aarch64-apple-darwin` to compile with clang, but unfortunately OpenMP doesn't work in this configuration.

Another fix is that `x86_64-unknown-freebsd` was actually using clang due to a faulty if statement, so i removed the faulty check.

Not sure what the correct way to build with clang and openmp on darwin is, the [build script](https://github.com/soedinglab/MMseqs2/blob/efacc6904ce3654110d1878943e16ddd0e7b1280/util/build_osx.sh#L29) downloads an openmp library from llvm.

**Comment by giordano** [comment]
Cool, thanks!  I'm still convinced there is something in the build system which was taking a wrong turn and assuming that we were building for an Intel platform.  We can revise this later, but at least we have something working for the time being.
