### PR TITLE
Reactant 0.0.213

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by wsmoses** [comment]
@giordano can i get some debugging help here?

**Comment by giordano** [comment]
I see two classes of issues:

* macOS debug builds:
   ``` [05:03:11] In file included from external/com_github_grpc_grpc/src/core/lib/transport/call_filters.cc:15:
   [05:03:11] In file included from external/com_github_grpc_grpc/src/core/lib/transport/call_filters.h:26:
   [05:03:11] In file included from external/com_google_absl/absl/log/check.h:37:
   [05:03:11] In file included from external/com_google_absl/absl/log/internal/check_impl.h:19:
   [05:03:11] external/com_google_absl/absl/log/internal/check_op.h:293:36: error: no matching function for call to 'Detect'
   [05:03:11]   293 | using CheckOpStreamType = decltype(detect_specialization::Detect<T>(0));
   [05:03:11]       |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   ```
   Sounds like XLA [uses](https://github.com/openxla/xla/blob/f5ec8747ff6844a8c97e0c8d679ff775fe4cd2d0/third_party/absl/workspace.bzl#L10) an [old version of absl](https://github.com/abseil/abseil-cpp/commit/54fac219c4ef0bc379dfffb0b8098725d77ac81b)
* linux cuda builds with cuda <= 12.4:
   ```
   [05:26:43] In file included from external/xla/xla/backends/profiler/gpu/cupti_tracer.cc:35:
   [05:26:43] bazel-out/k8-opt/bin/external/cuda_cupti/_virtual_includes/headers/third_party/gpus/cuda/extras/CUPTI/include/cupti_driver_cbid.h:9:14: error: multiple definition of ‘enum CUpti_driver_api_trace_cbid_enum’
   [05:26:43]     9 | typedef enum CUpti_driver_api_trace_cbid_enum {
   [05:26:43]       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   [05:26:43] In file included from bazel-out/k8-opt/bin/external/cuda_cupti/_virtual_includes/headers/third_party/gpus/cuda/extras/CUPTI/include/cupti.h:77,
   [05:26:43]                  from external/xla/xla/backends/profiler/gpu/cupti_tracer.h:26,
   [05:26:43]                  from external/xla/xla/backends/profiler/gpu/cupti_tracer.cc:16:
   [05:26:43] external/cuda_cupti/include/cupti_driver_cbid.h:9:14: note: previous definition here
   [05:26:43]     9 | typedef enum CUpti_driver_api_trace_cbid_enum {
   [05:26:43]       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   [05:26:43] bazel-out/k8-opt/bin/external/cuda_cupti/_virtual_includes/headers/third_party/gpus/cuda/extras/CUPTI/include/cupti_driver_cbid.h:724:3: error: conflicting declaration ‘typedef int CUpti_driver_api_trace_cbid’
   [05:26:43]   724 | } CUpti_driver_api_trace_cbid;
   [05:26:43]       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
   [05:26:43] external/cuda_cupti/include/cupti_driver_cbid.h:724:3: note: previous declaration as ‘typedef enum CUpti_driver_api_trace_cbid_enum CUpti_driver_api_trace_cbid’
   [05:26:43]   724 | } CUpti_driver_api_trace_cbid;
   [05:26:43]       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
   ```

Honestly they both look upstream errors to me.

**Comment by giordano** [comment]
I had tried already this morning to figure out where `external/cuda_cupti/_virtual_includes/headers/third_party/gpus/cuda/extras/CUPTI/include/cupti_driver_cbid.h` and `external/cuda_cupti/include/cupti_driver_cbid.h` are coming from, because it looks extremely fishy to me that the same package (cupti) is providing different definitions of the same type, but I got completely lost in bazel-land and I gave up.
