### PR TITLE
New Recipe: UCC_jll

### PR DESCRIPTION
**Pull request by krasow**
This recipe adds [UCC](https://github.com/openucx/ucc) v1.6.0 with built with UCX and CUDA on x86 platforms. In addition, it supports CPU only on x86 and aarch64. 

I am waiting for #13039 to be merged as this build depends directly on this. This PR will be set as a draft until then. This build recipe matches the platform configuration in the UCX PR.

LICENSE: [BSD-3-Clause](https://github.com/openucx/ucc/blob/master/LICENSE)

### CODE REVIEW

**Comment by krasow** [comment]
Adding NCCL broke the CUDA 13 build. 
```
[20:23:51] /workspace/destdir/lib/libnccl.so: undefined reference to `pthread_setattr_default_np@GLIBC_2.18'3`
```
 which seems to relate to the [CUDA 13 NCCL_jll patch ](https://github.com/JuliaPackaging/Yggdrasil/tree/master/N/NCCL/bundled/patches)

```
sandbox:${WORKSPACE}/srcdir/ucc # ldd /workspace/destdir/lib/libnccl.so | grep libc
        libstdc++.so.6 => /usr/lib/csl-glibc-x86_64/libstdc++.so.6 (0x00007f1281c85000)
        libgcc_s.so.1 => /usr/lib/csl-glibc-x86_64/libgcc_s.so.1 (0x00007f1281b90000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f1281994000)

sandbox:${WORKSPACE}/srcdir/ucc # nm -D /lib64/libc.so.6 | grep pthread_setattr
000000000008b470 T pthread_setattr_default_np@@GLIBC_2.34
000000000008b470 T pthread_setattr_default_np@GLIBC_2.18
```

**Comment by krasow** [comment]
The failing build had version `NCCL_jll v2.28.3`. By forcing `v2.27.7`, this build bug is resolved. The [NCCL patch](https://github.com/JuliaPackaging/Yggdrasil/tree/master/N/NCCL/bundled/patches) seems to break things.

**Comment by krasow** [comment]
@avik-pal I believe this NCCL_jll patch might be causing issues for NCCL dependent applications in BinaryBuilder.

**Comment by krasow** [comment]
@giordano Good to go. #13039 is now merged so this package (UCC) build using the new 1.20 UCX.
