### PR TITLE
[libpolymake_julia] Build with libjulia 1.11.0 (and thus for julia 1.14)

### PR DESCRIPTION
**Pull request by lgoettgens**

### CODE REVIEW

**Comment by benlorenz** [comment]
I would prefer to keep the old compat string, since I think an error like this
https://github.com/oscar-system/Polymake.jl/actions/runs/19012599376/job/54295724663#step:8:62
```
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```
is better than the platform is not supported message or whatever precompilation error later on. It also appears during resolve, i.e. much earlier.
Having `>= 1.10` as a compat entry for a library depending on libjulia is not really valid since the soname depends on the minor version.

**Comment by lgoettgens** [comment]
Ah, that's what this piece of code was for. I'll revert that change here, and will also eventually look into upstreaming this to the libjulia common.jl as IMO this should already be used for libjulia_jll as well
