### PR TITLE
Add compiler shards for LLVM 14, 15 and 17.

### PR DESCRIPTION
**Pull request by maleadt**
For building POCL, I need a `clang` version that's compatible with the `libLLVM` that will be loaded at run time. I can't use the one from a `HostDependency`, because it doesn't support generating code for the target I'm working with. So instead I think I have to use `preferred_llvm_version`, matching that up with the LLVM version of the build.

However, it looks like we currently only provide:

```
julia> BinaryBuilder.BinaryBuilderBase.available_llvm_builds
8-element Vector{BinaryBuilderBase.LLVMBuild}:
 BinaryBuilderBase.LLVMBuild(v"6.0.1", NamedTuple())
 BinaryBuilderBase.LLVMBuild(v"7.1.0", NamedTuple())
 BinaryBuilderBase.LLVMBuild(v"8.0.1", NamedTuple())
 BinaryBuilderBase.LLVMBuild(v"9.0.1", NamedTuple())
 BinaryBuilderBase.LLVMBuild(v"11.0.1", NamedTuple())
 BinaryBuilderBase.LLVMBuild(v"12.0.0", NamedTuple())
 BinaryBuilderBase.LLVMBuild(v"13.0.1", NamedTuple())
 BinaryBuilderBase.LLVMBuild(v"16.0.6", NamedTuple())
```

This PR is the first step to extending that to cover all LLVM versions encountered in Julia. I just copied the previous version's directories, so this is probably incomplete.

### CODE REVIEW

**Comment by maleadt** [comment]
Hmm, that didn't do much. How does one generate these JLLs?

**Review by giordano — COMMENTED** [review]
You need also to update the sources at https://github.com/JuliaPackaging/Yggdrasil/blob/c44697f53fe36b467b438a9f93f34780a601598a/0_RootFS/llvm_common.jl#L27-L37

Stuff in the 0_RootFS directory is special, you have to build it yourself, following the instructions at 
https://github.com/JuliaPackaging/Yggdrasil/blob/c44697f53fe36b467b438a9f93f34780a601598a/0_RootFS/llvm_common.jl#L1-L19
See the note about the symlinks for the patches, to avoid duplicates.

One thing perhaps not clear in the instructions is that you should have `BinaryBuilderBase` `dev`-ed, so that you can open a PR from that once the build finishes.  You probably also need to have `squashfs_tools_jll` in the environment (not `dev`-ed though, that's only for BBB).

**Comment by maleadt** [comment]
Hm, this is proving more problematic than I anticipated.

LLVM 15 fails to build with:

```
[21:19:02] CMake Error at /workspace/srcdir/llvm-project/libunwind/src/CMakeLists.txt:109 (message):
[21:19:02]   Compiler doesn't support generation of unwind tables if exception support
[21:19:02]   is disabled.  Building libunwind DSO with runtime dependency on C++ ABI
[21:19:02]   library is not supported.
```

However, this is a misleading error message. According to https://github.com/llvm/llvm-project/issues/49139#issuecomment-1719583901, it's related to how the runtimes are built, and passing an explicit triple (`-DLLVM_HOST_TRIPLE`) should solve the issue. But we're already doing that...
Seeing how this is a failure in the runtime build, I tried backporting the big `compiler-rt-build-crt-in-runtimes-build` patch we carry for LLVM 16, but it doesn't really apply, and fixing the conflicts results in `crtbegin`/`crtend`-related compilation errors (which is what the patch touches, so I guess it doesn't really apply that far back). @gbaraldi Do you remember if this is the build failure you were referring to in https://github.com/JuliaPackaging/Yggdrasil/pull/7439#issue-1915663046?

LLVM 14 fails to build with:

```
[21:05:38] CMake Error at /workspace/srcdir/llvm-project/compiler-rt/cmake/config-ix.cmake:208 (message):
[21:05:38]   Please use architecture with 4 or 8 byte pointers.
[21:05:38] Call Stack (most recent call first):
[21:05:38]   /workspace/srcdir/llvm-project/compiler-rt/CMakeLists.txt:251 (include)
```

But that's once again misleading, the actual error seems to be:

```
Linking CXX executable cmTC_d4496
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d4496.dir/link.txt --verbose=1
/workspace/srcdir/llvm-project/llvm/build/./bin/clang++ --target=x86_64-linux-musl  -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wdelete-non-virtual-dtor -Wno-comment  -Wl,--version-script,/workspace/srcdir/llvm-project/llvm/build/runtimes/runtimes-bins/CMakeFiles/CMakeTmp/dummy.vers -L/workspace/destdir/x86_64-linux-musl/lib64 -Wl,-rpath-link,/workspace/destdir/x86_64-linux-musl/lib64  CMakeFiles/cmTC_d4496.dir/src.cxx.o -o cmTC_d4496
ld.lld: error: cannot open crtbeginS.o: No such file or directory
ld.lld: error: unable to find library -lc++
ld.lld: error: cannot open /workspace/srcdir/llvm-project/llvm/build/lib/clang/14.0.6/lib/linux/libclang_rt.builtins-x86_64.a: No such file or directory
ld.lld: error: cannot open /workspace/srcdir/llvm-project/llvm/build/lib/clang/14.0.6/lib/linux/libclang_rt.builtins-x86_64.a: No such file or directory
ld.lld: error: cannot open crtendS.o: No such file or directory
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

... where the path to the builtins is wrong, it should be `/workspace/srcdir/llvm-project/llvm/build/lib/clang/14.0.6/lib/x86_64-linux-musl/libclang_rt.builtins.a`.

**Comment by maleadt** [comment]
Oh interesting, forcing `LLVM_HOST_TRIPLE` to `x86_64-alpine-linux-musl` (instead of `x86_64-linux-musl` from `$target`) seems to work, for LLVM 15 at least.

**Comment by maleadt** [comment]
Bumped the Manifest to include the BinaryBuilderBase change, and verified that the shards work by compiling POCL.

**Review by giordano — APPROVED** [review]
Looks good, thanks!  Note that you can also update the manifest from https://github.com/JuliaPackaging/Yggdrasil/actions/workflows/update_manifest.yml
