### PR TITLE
iroh: New package

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

File: I/iroh/build_tarballs.jl [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+# (https://github.com/rust-lang/rust/issues/79609)
+filter!(p -> !(Sys.iswindows(p) && arch(p) == "i686"), platforms)
+
+# `ring` only ships assembly (and CPU feature detection) for x86, x86_64, arm
+# and aarch64.
+filter!(p -> arch(p) ∈ ("x86_64", "i686", "aarch64", "armv7l", "armv6l"), platforms)
+
+# Yggdrasil does not (yet!) support aarch64-*-freebsd for a modern Rust setup
+# (Remove this line once it is.)
+filter!(p -> !(arch(p) == "aarch64" && Sys.isfreebsd(p)), platforms)
```
Comment (ararslan) [inline I/iroh/build_tarballs.jl]: 🤔 It _should_ work, that was the whole point of my PR that you got over the finish line. (Thanks again!) Is it broken somehow?

Comment (ararslan) [reply I/iroh/build_tarballs.jl]: Based on the log from a CI job before you added this line, it looks like it was failing because it was looking for Rust 1.94, but we have FreeBSD AArch64 support as of Rust 1.97. Is it possible to specify 1.97?

Comment (eschnett) [reply I/iroh/build_tarballs.jl]: The version of BinaryBuilderBase which Yggdrasil uses has not yet been updated. That's the last bit, and I don't have the permissions (nor the experience). @giordano ?

Comment (giordano) [reply I/iroh/build_tarballs.jl]: Isn't it https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/488?

Comment (eschnett) [reply I/iroh/build_tarballs.jl]: Yes, that moved it into BBB. But isn't the Yggdrasil BBB version pinned? Or does it always use the latest master?

Comment (giordano) [reply I/iroh/build_tarballs.jl]: It's pinned in the manifest, which you update with https://github.com/JuliaPackaging/Yggdrasil/actions/workflows/update_manifest.yml

**Comment by ararslan** [comment]
Looks like the Rust crate `netdev` is failing due to an issue that was fixed in https://github.com/shellrow/netdev/pull/169, which is available in `netdev` v0.45.0, but the build is using v0.44.0.

File: I/iroh/build_tarballs.jl (hunk 1 above)
Comment (eschnett) [reply I/iroh/build_tarballs.jl]: There is now a rust build error in h2 v0.4.15 for this architecture:
```
[22:50:57]    Compiling h2 v0.4.15
[22:50:57] error[E0425]: cannot find value `SIOCGIFXMEDIA` in this scope
```

Comment (ararslan) [reply I/iroh/build_tarballs.jl]: Looks like the same issue as https://github.com/JuliaPackaging/Yggdrasil/pull/14348#issuecomment-5182738444

Comment (eschnett) [reply I/iroh/build_tarballs.jl]: Now fixed.

**Review by ararslan — APPROVED** [review]
Thanks for all the extra effort for FreeBSD AArch64 support 🙂
