### PR TITLE
[libcxxwrap-julia] Bump version to v0.9.0

### PR DESCRIPTION
**Pull request by barche**

### CODE REVIEW

**Comment by barche** [comment]
@fingolfin I'm getting libcxxwrap-julia build failures with:

```
Warning: Dependency libjulia_jll does not have a mapping for artifact libjulia for platform aarch64-apple-darwin20-libgfortran5-cxx11-julia_version+1.6.3
```
(log at https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=15748&view=logs&j=64e4dabb-4ec3-501c-2d64-463504d2fa74&t=884cc234-77a0-5797-1cd5-7376d470f420&l=60)

I tried 1.6.0 first, but that didn't do the trick. I believe this is the reason why later on julia_version.h is not found, any ideas?

Note that the freebsd versions are unrelated, this is a problem I need to fix in libcxxwrap-julia.

**Comment by giordano** [comment]
We have aarch64-apple-darwin and all armv6l-based platforms only for Julia v1.7.  I guess this was broken by #4160

**Comment by fingolfin** [comment]
Indeed. I think we'll have to adjust `libjulia_platforms`... It currently does this:
```julia
platforms = supported_platforms(; experimental=julia_version ≥ v"1.7")
```
We need to replace this and instead filter out the "new" (formerly: experimental) platforms when `julia_version` is 1.6.

Of course the next time platforms are added, this would have to be adjusted again; this could be avoided if instead of removing "new" platforms, we add an explicit list of platforms for 1.6... but I am not sure it's worth the hassle.

**Comment by fingolfin** [comment]
Maybe this patch will do it:
```patch
diff --git a/L/libjulia/common.jl b/L/libjulia/common.jl
index fd91350c..b3b7c5a4 100644
--- a/L/libjulia/common.jl
+++ b/L/libjulia/common.jl
@@ -6,7 +6,7 @@ include("../../fancy_toys.jl") # for get_addable_spec
 
 # return the platforms supported by libjulia
 function libjulia_platforms(julia_version)
-    platforms = supported_platforms(; experimental=julia_version ≥ v"1.7")
+    platforms = supported_platforms()
 
     # skip 32bit musl builds; they fail with this error:
     #    libunwind.so.8: undefined reference to `setcontext'
@@ -17,6 +17,12 @@ function libjulia_platforms(julia_version)
         filter!(p -> !(Sys.islinux(p) && arch(p) == "powerpc64le"), platforms)
     end
 
+    if julia_version < v"1.7"
+        # In Julia <= 1.6, skip macOS on ARM and Linux on armv6l
+        filter!(p -> !(Sys.isapple(p) && arch(p) == "aarch64"), platforms)
+        filter!(p -> arch(p) != "armv6l", platforms)
+    end
+
     if julia_version >= v"1.6"
         for p in platforms
             p["julia_version"] = string(julia_version)
```

**Comment by giordano** [comment]
Ugh, I didn't want this to trigger a rebuild of libjulia.  Ok, I'm going to open a new PR

**Comment by barche** [comment]
Thanks, if I understand correctly this needs a rebase onto the new master now?

**Comment by giordano** [comment]
CI runs on the merge commit, so it shouldn't be needed, I pushed after merging #4166. Only freebsd is failing now

**Comment by barche** [comment]
Should be OK now, thanks for the help!
