### PR TITLE
[libjulia] Update to latest master

### PR DESCRIPTION
**Pull request by lgoettgens**
libpolymake_julia has weird errors on julia 1.13.0-DEV, that we hope to fix by rebuilding libjulia, libcxxwrap, and finally libpolymake_julia

### CODE REVIEW

**Comment by lgoettgens** [comment]
For the julia-1.13 builds, there are some errors related to zstd:
```julia
[14:25:30] /opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: ./staticdata.dbg.obj: in function `jl_image_unpack_zstd':
[14:25:30] /workspace/srcdir/julia/src/staticdata.c:3671: undefined reference to `ZSTD_getFrameContentSize'
[14:25:30] /opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: /workspace/srcdir/julia/src/staticdata.c:3694: undefined reference to `ZSTD_decompress'
[14:25:30] collect2: error: ld returned 1 exit status
[14:25:30] make[1]: *** [Makefile:450: /workspace/srcdir/julia/usr/lib/libjulia-internal-debug.so.1.13.0] Error 1
[14:25:30] make[1]: Leaving directory '/workspace/srcdir/julia/src'
[14:25:30] make: *** [Makefile:108: julia-src-debug] Error 2
[14:25:30] /opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linuxmake: *** Waiting for unfinished jobs....
[14:25:30] -gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: ./staticdata.o: in function `jl_image_unpack_zstd':
[14:25:30] /workspace/srcdir/julia/src/staticdata.c:3671: undefined reference to `ZSTD_getFrameContentSize'
[14:25:30] /opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: /workspace/srcdir/julia/src/staticdata.c:3694: undefined reference to `ZSTD_decompress'
[14:25:30] collect2: error: ld returned 1 exit status
```
The calls to non-linkable functions have been introduced in https://github.com/JuliaLang/julia/pull/59227.

I tried some things locally, but didn't get it to work. Any ideas? (maybe @giordano @gbaraldi or @xal-0 have some input as they interacted with https://github.com/JuliaLang/julia/pull/59227)

**Comment by xal-0** [comment]
Hmm, `USE_SYSTEM_LLVM=1` may be the issue, since we add `CG_LLVMLINK += -lz -lzstd` only with it set to 0.

**Comment by lgoettgens** [comment]
> Hmm, `USE_SYSTEM_LLVM=1` may be the issue, since we add `CG_LLVMLINK += -lz -lzstd` only with it set to 0.

Thanks for the pointer and the fix on the julia side. To not have to wait for that, I now added a similar workaround to the libjulia recipe, that should be dropped again once https://github.com/JuliaLang/julia/pull/59475 is in.

**Comment by lgoettgens** [comment]
This is ready to be merged @benlorenz @fingolfin
